apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  selector:
    matchLabels:
      app: reactapp
      type: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: reactapp
        type: frontend
    spec:
      containers:
      - name: reactapp-container
        image: sankardockerdev/my-react-app:latest
        imagePullPolicy: "Always"
        env:
          - name: API_URL
            valueFrom: 
              configMapKeyRef:
                name: service-url 
                key: url
---
apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: reactapp
    type: frontend
