apiVersion: apps/v1
kind: Deployment
metadata:
  name: reactapp-deployment
spec:
  selector:
    matchLabels:
      app: reactapp
      type: frontend
  replicas: 2 
  template:
    metadata:
      labels:
        app: reactapp
        type: frontend
    spec:
      containers:
      - name: reactapp-container
        image: sankardockerdev/my-react-app:latest
        imagePullPolicy: Always