apiVersion: v1
kind: Service
metadata:
  name: react-service
  labels:
    app: react-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: reactapp
    type: frontend